-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2025-01-10 12:51:00 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE composition (
    pallet_id          INTEGER NOT NULL,
    product_id         INTEGER NOT NULL,
    number_of_products INTEGER NOT NULL
);

CREATE TABLE orders (
    order_id          INTEGER NOT NULL,
    id                INTEGER,
    order_date        DATE,
    number_of_pallets INTEGER NOT NULL,
    pallet_id         INTEGER NOT NULL,
    order_status      VARCHAR2(30) NOT NULL
);

ALTER TABLE orders ADD CONSTRAINT order_ck_1 CHECK ( number_of_pallets >= 0 );

ALTER TABLE orders ADD CONSTRAINT order_pk PRIMARY KEY ( order_id );

CREATE TABLE products (
    product_id INTEGER NOT NULL,
    category   VARCHAR2(20),
    type       VARCHAR2(30),
    weight     INTEGER,
    price      NUMBER(3, 2) NOT NULL
);

ALTER TABLE products ADD CONSTRAINT products_pk PRIMARY KEY ( product_id );

CREATE TABLE storage (
    pallet_id         INTEGER NOT NULL,
    number_of_pallets INTEGER,
    standard          INTEGER
);

ALTER TABLE storage ADD CONSTRAINT storage_ck_1 CHECK ( number_of_pallets >= 0 );

ALTER TABLE storage ADD CONSTRAINT storage_pk PRIMARY KEY ( pallet_id );

CREATE TABLE users (
    id           INTEGER NOT NULL,
    company_name VARCHAR2(30),
    login        VARCHAR2(30) NOT NULL,
    password     VARCHAR2(300) NOT NULL,
    country      VARCHAR2(15),
    user_type    VARCHAR2(6) DEFAULT 'CLIENT' NOT NULL,
    last_login   DATE
);

ALTER TABLE users ADD CONSTRAINT user_pk PRIMARY KEY ( id );

ALTER TABLE users ADD CONSTRAINT login_uni UNIQUE ( login );

ALTER TABLE users ADD CONSTRAINT password_uni UNIQUE ( password );

CREATE TABLE working_day (
    shift_work_id INTEGER NOT NULL,
    work_date     DATE,
    shift_nr      NUMBER(1) NOT NULL,
    workers       INTEGER,
    made_pallets  INTEGER NOT NULL,
    pallet_id     INTEGER NOT NULL
);

ALTER TABLE working_day ADD CONSTRAINT working_day_ck_1 CHECK ( made_pallets >= 0 );

ALTER TABLE working_day ADD CONSTRAINT working_day_pk PRIMARY KEY ( shift_work_id );

ALTER TABLE orders
    ADD CONSTRAINT order_storage_fk FOREIGN KEY ( pallet_id )
        REFERENCES storage ( pallet_id );

ALTER TABLE orders
    ADD CONSTRAINT order_user_fk FOREIGN KEY ( id )
        REFERENCES users ( id );

ALTER TABLE composition
    ADD CONSTRAINT tb_products_fk FOREIGN KEY ( product_id )
        REFERENCES products ( product_id );

ALTER TABLE composition
    ADD CONSTRAINT tb_storage_fk FOREIGN KEY ( pallet_id )
        REFERENCES storage ( pallet_id );

ALTER TABLE working_day
    ADD CONSTRAINT working_day_storage_fk FOREIGN KEY ( pallet_id )
        REFERENCES storage ( pallet_id );

CREATE SEQUENCE auto_increment_order_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER auto_trigger_order_id BEFORE
    INSERT ON orders
    FOR EACH ROW
    WHEN ( new.order_id IS NULL )
BEGIN
    :new.order_id := auto_increment_order_id.nextval;
END;
/

CREATE SEQUENCE auto_increment_product START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER auto_trigger_product BEFORE
    INSERT ON products
    FOR EACH ROW
    WHEN ( new.product_id IS NULL )
BEGIN
    :new.product_id := auto_increment_product.nextval;
END;
/

CREATE SEQUENCE pallet_id_auto_inc START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pallet_id_auto_trig BEFORE
    INSERT ON storage
    FOR EACH ROW
    WHEN ( new.pallet_id IS NULL )
BEGIN
    :new.pallet_id := pallet_id_auto_inc.nextval;
END;
/

CREATE SEQUENCE auto_increment_user_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER auto_trigger_user_id BEFORE
    INSERT ON users
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := auto_increment_user_id.nextval;
END;
/

CREATE SEQUENCE auto_work_increment_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER auto_work_trigger_id BEFORE
    INSERT ON working_day
    FOR EACH ROW
    WHEN ( new.shift_work_id IS NULL )
BEGIN
    :new.shift_work_id := auto_work_increment_id.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
